name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Transfer files to VPS
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" c:\Users\mmcgr\Desktop\dev\github\Deploy root@89.116.191.98:/root/deployTests/ 
